enum actia_ofono_vendor {
    OFONO_VENDOR_GEMALTO_CINT_AHS = 0x55 ,
    OFONO_VENDOR_GEMALTO_CINT_PLS62 = 0x5b ,
    OFONO_VENDOR_GEMALTO_CINT_PLS8 = 0x61 ,
	OFONO_VENDOR_GEMALTO_CINT_PLS83 = 0x66 ,
};
