    case RIL_E_SUCCESS: return "SUCCESS(0): Success";
    case RIL_E_RADIO_NOT_AVAILABLE: return "RADIO_NOT_AVAILABLE(1): If radio did not start or is resetting error";
    case RIL_E_GENERIC_FAILURE: return "GENERIC_FAILURE(2): Generic Failure error";
    case RIL_E_PASSWORD_INCORRECT: return "PASSWORD_INCORRECT(3): For PIN/PIN2 methods only error";
    case RIL_E_SIM_PIN2: return "SIM_PIN2(4): Operation requires SIM PIN2 to be entered error";
    case RIL_E_SIM_PUK2: return "SIM_PUK2(5): Operation requires SIM PIN2 to be entered error";
    case RIL_E_REQUEST_NOT_SUPPORTED: return "REQUEST_NOT_SUPPORTED(6): Not Supported request error";
    case RIL_E_CANCELLED: return "CANCELLED(7): Cancelled error";
    case RIL_E_OP_NOT_ALLOWED_DURING_VOICE_CALL: return "OP_NOT_ALLOWED_DURING_VOICE_CALL(8): Data operation are not allowed during voice call on a Class C GPRS device error";
    case RIL_E_OP_NOT_ALLOWED_BEFORE_REG_TO_NW: return "OP_NOT_ALLOWED_BEFORE_REG_TO_NW(9): Data operation are not allowed before device registers in network error";
    case RIL_E_SMS_SEND_FAIL_RETRY: return "SMS_SEND_FAIL_RETRY(10): Fail to send SMS and need retry error";
    case RIL_E_SIM_ABSENT: return "SIM_ABSENT(11): Fail to set the location where CDMA subscription shall be retrieved because of SIM or RUIM are absent error";
    case RIL_E_SUBSCRIPTION_NOT_AVAILABLE: return "SUBSCRIPTION_NOT_AVAILABLE(12): Fail to find CDMA subscription from specified location error";
    case RIL_E_MODE_NOT_SUPPORTED: return "MODE_NOT_SUPPORTED(13): Hardware does not support preferred network type error";
    case RIL_E_FDN_CHECK_FAILURE: return "FDN_CHECK_FAILURE(14): Command failed because recipient is not on FDN list error";
    case RIL_E_ILLEGAL_SIM_OR_ME: return "ILLEGAL_SIM_OR_ME(15): Network selection failed due to illegal SIM or ME error";
    case RIL_E_MISSING_RESOURCE: return "MISSING_RESOURCE(16): No logical channel available error";
    case RIL_E_NO_SUCH_ELEMENT: return "NO_SUCH_ELEMENT(17): Application not found on SIM error";
    case RIL_E_DIAL_MODIFIED_TO_USSD: return "DIAL_MODIFIED_TO_USSD(18): DIAL request modified to USSD error";
    case RIL_E_DIAL_MODIFIED_TO_SS: return "DIAL_MODIFIED_TO_SS(19): DIAL request modified to SS error";
    case RIL_E_DIAL_MODIFIED_TO_DIAL: return "DIAL_MODIFIED_TO_DIAL(20): DIAL request modified to DIAL with different data error";
    case RIL_E_USSD_MODIFIED_TO_DIAL: return "USSD_MODIFIED_TO_DIAL(21): USSD request modified to DIAL error";
    case RIL_E_USSD_MODIFIED_TO_SS: return "USSD_MODIFIED_TO_SS(22): USSD request modified to SS error";
    case RIL_E_USSD_MODIFIED_TO_USSD: return "USSD_MODIFIED_TO_USSD(23): USSD request modified to different USSD request error";
    case RIL_E_SS_MODIFIED_TO_DIAL: return "SS_MODIFIED_TO_DIAL(24): SS request modified to DIAL error";
    case RIL_E_SS_MODIFIED_TO_USSD: return "SS_MODIFIED_TO_USSD(25): SS request modified to USSD error";
    case RIL_E_SUBSCRIPTION_NOT_SUPPORTED: return "SUBSCRIPTION_NOT_SUPPORTED(26): Subscription not supported error";
    case RIL_E_SS_MODIFIED_TO_SS: return "SS_MODIFIED_TO_SS(27): SS request modified to different SS request error";
    case RIL_E_LCE_NOT_SUPPORTED: return "LCE_NOT_SUPPORTED(36): LCE service not supported error";
    case RIL_E_NO_MEMORY: return "NO_MEMORY(37): Not sufficient memory to process the request error";
    case RIL_E_INTERNAL_ERR: return "INTERNAL_ERR(38): Hit unexpected vendor internal error scenario";
    case RIL_E_SYSTEM_ERR: return "SYSTEM_ERR(39): Hit platform or system error";
    case RIL_E_MODEM_ERR: return "MODEM_ERR(40): Hit unexpected modem error";
    case RIL_E_INVALID_STATE: return "INVALID_STATE(41): Unexpected request for the current state error";
    case RIL_E_NO_RESOURCES: return "NO_RESOURCES(42): Not sufficient resource to process the request error";
    case RIL_E_SIM_ERR: return "SIM_ERR(43): Received error from SIM card";
    case RIL_E_INVALID_ARGUMENTS: return "INVALID_ARGUMENTS(44): Received invalid arguments in request error";
    case RIL_E_INVALID_SIM_STATE: return "INVALID_SIM_STATE(45): Cannot process the request in current SIM state error";
    case RIL_E_INVALID_MODEM_STATE: return "INVALID_MODEM_STATE(46): Cannot process the request in current Modem state error";
    case RIL_E_INVALID_CALL_ID: return "INVALID_CALL_ID(47): Received invalid call id in request error";
    case RIL_E_NO_SMS_TO_ACK: return "NO_SMS_TO_ACK(48): ACK received when there is no SMS to ack error";
    case RIL_E_NETWORK_ERR: return "NETWORK_ERR(49): Received error from network";
    case RIL_E_REQUEST_RATE_LIMITED: return "REQUEST_RATE_LIMITED(50): Operation denied due to overly-frequent requests error";
    case RIL_E_SIM_BUSY: return "SIM_BUSY(51): SIM is busy error";
    case RIL_E_SIM_FULL: return "SIM_FULL(52): The target EF is full error";
    case RIL_E_NETWORK_REJECT: return "NETWORK_REJECT(53): Request is rejected by network error";
    case RIL_E_OPERATION_NOT_ALLOWED: return "OPERATION_NOT_ALLOWED(54): Not allowed the request now error";
    case RIL_E_EMPTY_RECORD: return "EMPTY_RECORD(55): The request record is empty error";
    case RIL_E_INVALID_SMS_FORMAT: return "INVALID_SMS_FORMAT(56): Invalid SMS format error";
    case RIL_E_ENCODING_ERR: return "ENCODING_ERR(57): Message not encoded properly error";
    case RIL_E_INVALID_SMSC_ADDRESS: return "INVALID_SMSC_ADDRESS(58): SMSC address specified is invalid error";
    case RIL_E_NO_SUCH_ENTRY: return "NO_SUCH_ENTRY(59): No such entry present to perform the request error";
    case RIL_E_NETWORK_NOT_READY: return "NETWORK_NOT_READY(60): Network is not ready to perform the request error";
    case RIL_E_NOT_PROVISIONED: return "NOT_PROVISIONED(61): Device does not have this value provisioned error";
    case RIL_E_NO_SUBSCRIPTION: return "NO_SUBSCRIPTION(62): Device does not have subscription error";
    case RIL_E_NO_NETWORK_FOUND: return "NO_NETWORK_FOUND(63): Network cannot be found error";
    case RIL_E_DEVICE_IN_USE: return "DEVICE_IN_USE(64): Operation cannot be performed because the device is currently in use error";
    case RIL_E_ABORTED: return "ABORTED(65): Operation aborted error";
    case RIL_E_INCOMPATIBLE_STATE: return "INCOMPATIBLE_STATE(90): Operation cannot be performed because the device is in incompatible state error";
    case RIL_E_NO_EFFECT: return "NO_EFFECT(101): Given request had to no effect error";
    case RIL_E_DEVICE_NOT_READY: return "DEVICE_NOT_READY(102): Device not ready error";
    case RIL_E_MISSING_ARGUMENTS: return "MISSING_ARGUMENTS(103): Missing one or more arguments error";
    case RIL_E_FILE_NOT_FOUND: return "FILE_NOT_FOUND(104): Required configuration file is missing error";
    case RIL_E_PIN_PERM_BLOCKED: return "PIN_PERM_BLOCKED(201): PIN is permanently blocked. The SIM is unusable. error";
    case RIL_E_PIN_BLOCKED: return "PIN_BLOCKED(202): PIN is blocked. Unblock operation must be issued. error";
    case RIL_E_MALFORMED_MSG: return "MALFORMED_MSG(1001): Message was not formulated correctly by the control point or the message was corrupted during transmission error";
    case RIL_E_INTERNAL: return "INTERNAL(1003): Internal error";
    case RIL_E_CLIENT_IDS_EXHAUSTED: return "CLIENT_IDS_EXHAUSTED(1005): Client IDs exhausted error";
    case RIL_E_UNABORTABLE_TRANSACTION: return "UNABORTABLE_TRANSACTION(1006): The specified transaction could not be aborted error";
    case RIL_E_INVALID_CLIENT_ID: return "INVALID_CLIENT_ID(1007): Could not find clients request error";
    case RIL_E_NO_THRESHOLDS: return "NO_THRESHOLDS(1008): No thresholds specified in enable signal strength error";
    case RIL_E_INVALID_HANDLE: return "INVALID_HANDLE(1009): Invalid client handle was received error";
    case RIL_E_INVALID_PROFILE: return "INVALID_PROFILE(1010): Invalid profile index specified error";
    case RIL_E_INVALID_PINID: return "INVALID_PINID(1011): PIN in the request is invalid. error";
    case RIL_E_INCORRECT_PIN: return "INCORRECT_PIN(1012): PIN in the request is incorrect. error";
    case RIL_E_CALL_FAILED: return "CALL_FAILED(1014): Call origination failed in the lower layers error";
    case RIL_E_OUT_OF_CALL: return "OUT_OF_CALL(1015): Request issued when packet data session disconnected error";
    case RIL_E_MISSING_ARG: return "MISSING_ARG(1017): TLV was missing in the request. error";
    case RIL_E_ARG_TOO_LONG: return "ARG_TOO_LONG(1019): Path in the request was too long. error";
    case RIL_E_INVALID_TX_ID: return "INVALID_TX_ID(1022): The transaction ID supplied in the request does not match any pending transaction i.e. either the transaction was not received or it is already executed by the device error";
    case RIL_E_OP_NETWORK_UNSUPPORTED: return "OP_NETWORK_UNSUPPORTED(1024): Selected operation is not supported by the network error";
    case RIL_E_OP_DEVICE_UNSUPPORTED: return "OP_DEVICE_UNSUPPORTED(1025): Operation is not supported by device or SIM card error";
    case RIL_E_NO_FREE_PROFILE: return "NO_FREE_PROFILE(1027): Maximum number of profiles are stored in the device and there is no more storage available to create a new profile error";
    case RIL_E_INVALID_PDP_TYPE: return "INVALID_PDP_TYPE(1028): PDP type specified is not supported error";
    case RIL_E_INVALID_TECH_PREF: return "INVALID_TECH_PREF(1029): Invalid technology preference error";
    case RIL_E_INVALID_PROFILE_TYPE: return "INVALID_PROFILE_TYPE(1030): Invalid profile type is specified error";
    case RIL_E_INVALID_SERVICE_TYPE: return "INVALID_SERVICE_TYPE(1031): Invalid service type error";
    case RIL_E_INVALID_REGISTER_ACTION: return "INVALID_REGISTER_ACTION(1032): Invalid register action value specified in request error";
    case RIL_E_INVALID_PS_ATTACH_ACTION: return "INVALID_PS_ATTACH_ACTION(1033): Invalid PS attach action value specified in request error";
    case RIL_E_AUTHENTICATION_FAILED: return "AUTHENTICATION_FAILED(1034): Authentication error";
    case RIL_E_SIM_NOT_INITIALIZED: return "SIM_NOT_INITIALIZED(1037): PIN is not yet initialized because the SIM initialization has not finished. Try the PIN operation later. error";
    case RIL_E_MAX_QOS_REQUESTS_IN_USE: return "MAX_QOS_REQUESTS_IN_USE(1038): Maximum QoS requests in use error";
    case RIL_E_INCORRECT_FLOW_FILTER: return "INCORRECT_FLOW_FILTER(1039): Incorrect flow filter error";
    case RIL_E_NETWORK_QOS_UNAWARE: return "NETWORK_QOS_UNAWARE(1040): Network QoS unaware error";
    case RIL_E_INVALID_ID: return "INVALID_ID(1041): Invalid call ID was sent in the request error";
    case RIL_E_REQUESTED_NUM_UNSUPPORTED: return "REQUESTED_NUM_UNSUPPORTED(1042): Requested message ID is not supported by the currently running software error";
    case RIL_E_INTERFACE_NOT_FOUND: return "INTERFACE_NOT_FOUND(1043): Cannot retrieve the FMC interface error";
    case RIL_E_FLOW_SUSPENDED: return "FLOW_SUSPENDED(1044): Flow suspended error";
    case RIL_E_INVALID_DATA_FORMAT: return "INVALID_DATA_FORMAT(1045): Invalid data format error";
    case RIL_E_GENERAL: return "GENERAL(1046): General error";
    case RIL_E_UNKNOWN: return "UNKNOWN(1047): Unknown error";
    case RIL_E_INVALID_ARG: return "INVALID_ARG(1048): Parameters passed as input were invalid error";
    case RIL_E_INVALID_INDEX: return "INVALID_INDEX(1049): MIP profile index is not within the valid range error";
    case RIL_E_NO_ENTRY: return "NO_ENTRY(1050): No message exists at the specified memory storage designation error";
    case RIL_E_DEVICE_STORAGE_FULL: return "DEVICE_STORAGE_FULL(1051): Memory storage specified in the request is full error";
    case RIL_E_CAUSE_CODE: return "CAUSE_CODE(1054): There was an error in the request";
    case RIL_E_MESSAGE_NOT_SENT: return "MESSAGE_NOT_SENT(1055): Message could not be sent error";
    case RIL_E_MESSAGE_DELIVERY_FAILURE: return "MESSAGE_DELIVERY_FAILURE(1056): Message could not be delivered error";
    case RIL_E_INVALID_MESSAGE_ID: return "INVALID_MESSAGE_ID(1057): Message ID specified for the message is invalid error";
    case RIL_E_ENCODING: return "ENCODING(1058): Message is not encoded properly error";
    case RIL_E_AUTHENTICATION_LOCK: return "AUTHENTICATION_LOCK(1059): Maximum number of authentication failures has been reached error";
    case RIL_E_INVALID_TRANSITION: return "INVALID_TRANSITION(1060): Selected operating mode transition from the current operating mode is invalid error";
    case RIL_E_NOT_A_MCAST_IFACE: return "NOT_A_MCAST_IFACE(1061): Not a MCAST interface error";
    case RIL_E_MAX_MCAST_REQUESTS_IN_USE: return "MAX_MCAST_REQUESTS_IN_USE(1062): MCAST request in use error";
    case RIL_E_INVALID_MCAST_HANDLE: return "INVALID_MCAST_HANDLE(1063): An invalid MCAST handle error";
    case RIL_E_INVALID_IP_FAMILY_PREF: return "INVALID_IP_FAMILY_PREF(1064): IP family preference is invalid error";
    case RIL_E_SESSION_INACTIVE: return "SESSION_INACTIVE(1065): Session inactive error";
    case RIL_E_SESSION_INVALID: return "SESSION_INVALID(1066): Session not valid error";
    case RIL_E_SESSION_OWNERSHIP: return "SESSION_OWNERSHIP(1067): Session ownership error";
    case RIL_E_INSUFFICIENT_RESOURCES: return "INSUFFICIENT_RESOURCES(1068): Response is longer than the maximum supported size error";
    case RIL_E_DISABLED: return "DISABLED(1069): Disabled error";
    case RIL_E_INVALID_OPERATION: return "INVALID_OPERATION(1070): Device is not expecting the request. error";
    case RIL_E_INVALID_QMI_CMD: return "INVALID_QMI_CMD(1071): Invalid QMI command error";
    case RIL_E_TPDU_TYPE: return "TPDU_TYPE(1072): Message in memory contains a TPDU type that cannot be read error";
    case RIL_E_SMSC_ADDR: return "SMSC_ADDR(1073): SMSC address specified is invalid error";
    case RIL_E_INFO_UNAVAILABLE: return "INFO_UNAVAILABLE(1074): Information is not available error";
    case RIL_E_SEGMENT_TOO_LONG: return "SEGMENT_TOO_LONG(1075): PRL segment size is too large error";
    case RIL_E_SEGMENT_ORDER: return "SEGMENT_ORDER(1076): PRL segment order is incorrect error";
    case RIL_E_BUNDLING_NOT_SUPPORTED: return "BUNDLING_NOT_SUPPORTED(1077): Bundling not supported error";
    case RIL_E_OP_PARTIAL_FAILURE: return "OP_PARTIAL_FAILURE(1078): Some personalization codes were set but an error prevented";
    case RIL_E_POLICY_MISMATCH: return "POLICY_MISMATCH(1079): Network policy does not match a valid NAT error";
    case RIL_E_SIM_FILE_NOT_FOUND: return "SIM_FILE_NOT_FOUND(1080): File is not present on the card. error";
    case RIL_E_EXTENDED_INTERNAL: return "EXTENDED_INTERNAL(1081): error from the the DS profile module, the extended";
    case RIL_E_ACCESS_DENIED: return "ACCESS_DENIED(1082): Access to the requested file is denied. This can occur when there is an attempt to access a PIN-protected file. error";
    case RIL_E_HARDWARE_RESTRICTED: return "HARDWARE_RESTRICTED(1083): Selected operating mode is invalid with the current wireless disable setting error";
    case RIL_E_ACK_NOT_SENT: return "ACK_NOT_SENT(1084): ACK could not be sent error";
    case RIL_E_INJECT_TIMEOUT: return "INJECT_TIMEOUT(1085): Inject timeout error";
    case RIL_E_FDN_RESTRICT: return "FDN_RESTRICT(1091): FDN restriction error";
    case RIL_E_SUPS_FAILURE_CAUSE: return "SUPS_FAILURE_CAUSE(1092): Indicates supplementary services failure information; error";
    case RIL_E_NO_RADIO: return "NO_RADIO(1093): Radio is not available error";
    case RIL_E_NOT_SUPPORTED: return "NOT_SUPPORTED(1094): Operation is not supported error";
    case RIL_E_CARD_CALL_CONTROL_FAILED: return "CARD_CALL_CONTROL_FAILED(1096): SIM/R-UIM call control failed error";
    case RIL_E_NETWORK_ABORTED: return "NETWORK_ABORTED(1097): Operation was released abruptly by the network error";
    case RIL_E_MSG_BLOCKED: return "MSG_BLOCKED(1098): Message blocked error";
    case RIL_E_INVALID_SESSION_TYPE: return "INVALID_SESSION_TYPE(1100): Invalid session type error";
    case RIL_E_INVALID_PB_TYPE: return "INVALID_PB_TYPE(1101): Invalid Phone Book type error";
    case RIL_E_NO_SIM: return "NO_SIM(1102): Action is being performed on a SIM that is not initialized. error";
    case RIL_E_PB_NOT_READY: return "PB_NOT_READY(1103): Phone Book not ready error";
    case RIL_E_PIN_RESTRICTION: return "PIN_RESTRICTION(1104): PIN restriction error";
    case RIL_E_PIN2_RESTRICTION: return "PIN2_RESTRICTION(1105): PIN2 restriction error";
    case RIL_E_PUK_RESTRICTION: return "PUK_RESTRICTION(1106): PUK restriction error";
    case RIL_E_PUK2_RESTRICTION: return "PUK2_RESTRICTION(1107): PUK2 restriction error";
    case RIL_E_PB_ACCESS_RESTRICTED: return "PB_ACCESS_RESTRICTED(1108): Phone Book access restricted error";
    case RIL_E_PB_DELETE_IN_PROG: return "PB_DELETE_IN_PROG(1109): Phone Book delete in progress error";
    case RIL_E_PB_TEXT_TOO_LONG: return "PB_TEXT_TOO_LONG(1110): Phone Book text too long error";
    case RIL_E_PB_NUMBER_TOO_LONG: return "PB_NUMBER_TOO_LONG(1111): Phone Book number too long error";
    case RIL_E_PB_HIDDEN_KEY_RESTRICTION: return "PB_HIDDEN_KEY_RESTRICTION(1112): Phone Book hidden key restriction error";
    case RIL_E_PB_NOT_AVAILABLE: return "PB_NOT_AVAILABLE(1113): Phone Book not available error";
    case RIL_E_DEVICE_MEMORY_ERROR: return "DEVICE_MEMORY_ERROR(1114): Device memory error";
    case RIL_E_NO_PERMISSION: return "NO_PERMISSION(1115): No permission error";
    case RIL_E_TOO_SOON: return "TOO_SOON(1116): Too soon error";
    case RIL_E_TIME_NOT_ACQUIRED: return "TIME_NOT_ACQUIRED(1117): Time not acquired error";
    case RIL_E_OP_IN_PROGRESS: return "OP_IN_PROGRESS(1118): Operation is in progress error";
    case RIL_E_DS_PROFILE_REG_RESULT_FAIL: return "DS_PROFILE_REG_RESULT_FAIL(2001): General failure error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_INVAL_HNDL: return "DS_PROFILE_REG_RESULT_ERR_INVAL_HNDL(2002): Request contains an invalid profile handle error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_INVAL_OP: return "DS_PROFILE_REG_RESULT_ERR_INVAL_OP(2003): Invalid operation was requested error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_TYPE: return "DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_TYPE(2004): Request contains an invalid technology type error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_NUM: return "DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_NUM(2005): Request contains an invalid profile number error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_INVAL_IDENT: return "DS_PROFILE_REG_RESULT_ERR_INVAL_IDENT(2006): Request contains an invalid profile identifier error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_INVAL: return "DS_PROFILE_REG_RESULT_ERR_INVAL(2007): Request contains an invalid argument other than profile number and profile identifier received error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_LIB_NOT_INITED: return "DS_PROFILE_REG_RESULT_ERR_LIB_NOT_INITED(2008): Profile registry has not been initialized yet error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_LEN_INVALID: return "DS_PROFILE_REG_RESULT_ERR_LEN_INVALID(2009): Request contains a parameter with invalid length error";
    case RIL_E_DS_PROFILE_REG_RESULT_LIST_END: return "DS_PROFILE_REG_RESULT_LIST_END(2010): End of the profile list was reached while searching for the requested profile error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_INVAL_SUBS_ID: return "DS_PROFILE_REG_RESULT_ERR_INVAL_SUBS_ID(2011): Request contains an invalid subscription identifier error";
    case RIL_E_DS_PROFILE_REG_INVAL_PROFILE_FAMILY: return "DS_PROFILE_REG_INVAL_PROFILE_FAMILY(2012): Request contains an invalid profile family error";
    case RIL_E_DS_PROFILE_REG_PROFILE_VERSION_MISMATCH: return "DS_PROFILE_REG_PROFILE_VERSION_MISMATCH(2013): Version mismatch error";
    case RIL_E_REG_RESULT_ERR_OUT_OF_MEMORY: return "REG_RESULT_ERR_OUT_OF_MEMORY(2014): Out of memory error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_FILE_ACCESS: return "DS_PROFILE_REG_RESULT_ERR_FILE_ACCESS(2015): File access error";
    case RIL_E_DS_PROFILE_REG_RESULT_ERR_EOF: return "DS_PROFILE_REG_RESULT_ERR_EOF(2016): End of field error";
    case RIL_E_REG_RESULT_ERR_VALID_FLAG_NOT_SET: return "REG_RESULT_ERR_VALID_FLAG_NOT_SET(2017): A valid flag is not set error";
    case RIL_E_REG_RESULT_ERR_OUT_OF_PROFILES: return "REG_RESULT_ERR_OUT_OF_PROFILES(2018): Out of profiles error";
    case RIL_E_REG_RESULT_NO_EMERGENCY_PDN_SUPPORT: return "REG_RESULT_NO_EMERGENCY_PDN_SUPPORT(2019): No emergency PDN support error";
    case RIL_E_V2X_ERR_EXCEED_MAX: return "V2X_ERR_EXCEED_MAX(3000): Exceed max allowed number error";
    case RIL_E_V2X_ERR_V2X_DISABLED: return "V2X_ERR_V2X_DISABLED(3001): V2x mode was not enabled error";
    case RIL_E_V2X_ERR_UNKNOWN_SERVICE_ID: return "V2X_ERR_UNKNOWN_SERVICE_ID(3002): The service id unknown error";
    case RIL_E_V2X_ERR_SRV_ID_L2_ADDRS_NOT_COMPATIBLE: return "V2X_ERR_SRV_ID_L2_ADDRS_NOT_COMPATIBLE(3003): The service Id mismatch with L2 addr error";
    case RIL_E_V2X_ERR_PORT_UNAVAIL: return "V2X_ERR_PORT_UNAVAIL(3004): The port was occupied by others error";
    case RIL_E_DS_PROFILE_3GPP_INVAL_PROFILE_FAMILY: return "DS_PROFILE_3GPP_INVAL_PROFILE_FAMILY(4097): Request contains an invalid 3GPP profile family error";
    case RIL_E_DS_PROFILE_3GPP_ACCESS_ERR: return "DS_PROFILE_3GPP_ACCESS_ERR(4098): error was encountered while accessing the 3GPP profiles";
    case RIL_E_DS_PROFILE_3GPP_CONTEXT_NOT_DEFINED: return "DS_PROFILE_3GPP_CONTEXT_NOT_DEFINED(4099): Specified 3GPP profile does not have a valid context error";
    case RIL_E_DS_PROFILE_3GPP_VALID_FLAG_NOT_SET: return "DS_PROFILE_3GPP_VALID_FLAG_NOT_SET(4100): Specified 3GPP profile is marked invalid error";
    case RIL_E_DS_PROFILE_3GPP_READ_ONLY_FLAG_SET: return "DS_PROFILE_3GPP_READ_ONLY_FLAG_SET(4101): Specified 3GPP profile is marked read-only error";
    case RIL_E_DS_PROFILE_3GPP_ERR_OUT_OF_PROFILES: return "DS_PROFILE_3GPP_ERR_OUT_OF_PROFILES(4102): Creation of a new 3GPP profile failed because the limit of 16 profiles has already been reached error";
    case RIL_E_DS_PROFILE_3GPP2_ERR_INVALID_IDENT_FOR_PROFILE: return "DS_PROFILE_3GPP2_ERR_INVALID_IDENT_FOR_PROFILE(4353): Invalid profile identifier was received as part of the 3GPP2 profile modification request error";
    case RIL_E_DS_PROFILE_3GPP2_ERR_OUT_OF_PROFILE: return "DS_PROFILE_3GPP2_ERR_OUT_OF_PROFILE(4354): Creation of a new 3GPP2 profile failed because the limit has already been reached error";
    case RIL_E_INTERNAL_ERROR: return "INTERNAL_ERROR(-1): Internal error";
    case RIL_E_SERVICE_ERROR: return "SERVICE_ERROR(-2): Service error";
    case RIL_E_TIMEOUT_ERROR: return "TIMEOUT_ERROR(-3): Timeout error";
    case RIL_E_EXTENDED_ERROR: return "EXTENDED_ERROR(-4): Extended error";
    case RIL_E_PORT_NOT_OPEN_ERROR: return "PORT_NOT_OPEN_ERROR(-5): Port not open";
    case RIL_E_MEMCOPY_ERROR: return "MEMCOPY_ERROR(-13): Memory copy error";
    case RIL_E_INVALID_TRANSACTION: return "INVALID_TRANSACTION(-14): Invalid transaction error";
    case RIL_E_ALLOCATION_FAILURE: return "ALLOCATION_FAILURE(-15): Allocation failure error";
    case RIL_E_TRANSPORT_ERROR: return "TRANSPORT_ERROR(-16): Transport error";
    case RIL_E_PARAM_ERROR: return "PARAM_ERROR(-17): Parameter error";
    case RIL_E_INVALID_CLIENT: return "INVALID_CLIENT(-18): Invalid client error";
    case RIL_E_FRAMEWORK_NOT_READY: return "FRAMEWORK_NOT_READY(-19): Framework not ready error";
    case RIL_E_INVALID_SIGNAL: return "INVALID_SIGNAL(-20): Invalid signal error";
    case RIL_E_TRANSPORT_BUSY_ERROR: return "TRANSPORT_BUSY_ERROR(-21): Transport busy error";
    case RIL_E_SUBSYSTEM_UNAVAILABLE: return "SUBSYSTEM_UNAVAILABLE(5000): Underlying service currently unavailable error";
    case RIL_E_OPERATION_TIMEOUT: return "OPERATION_TIMEOUT(5001): Timeout error";
    case RIL_E_ROLLBACK_FAILED: return "ROLLBACK_FAILED(5002): Rollback to initial state failed error";
    case RIL_E_ROT_ALREADY_SET: return "ROT_ALREADY_SET(5003): Root of trust already configured error";
    case RIL_E_UNSUPPORTED_PURPOSE: return "UNSUPPORTED_PURPOSE(5004): Unsupported use of the key error";
    case RIL_E_INCOMPATIBLE_PURPOSE: return "INCOMPATIBLE_PURPOSE(5005): Incompatible purpose error";
    case RIL_E_UNSUPPORTED_ALGO: return "UNSUPPORTED_ALGO(5006): Unsupported algorithm error";
    case RIL_E_INCOMPATIBLE_ALGO: return "INCOMPATIBLE_ALGO(5007): Incompatible algorithm error";
    case RIL_E_UNSUPPORTED_KEY_SIZE: return "UNSUPPORTED_KEY_SIZE(5008): Unsupported key size error";
    case RIL_E_UNSUPPORTED_BLOCK_MODE: return "UNSUPPORTED_BLOCK_MODE(5009): Unsupported block mode error";
    case RIL_E_INCOMPATIBLE_BLOCK_MODE: return "INCOMPATIBLE_BLOCK_MODE(5010): Incompatible block mode error";
    case RIL_E_UNSUPPORTED_MAC_LEN: return "UNSUPPORTED_MAC_LEN(5011): Unsupported MAC length error";
    case RIL_E_UNSUPPORTED_PADDING_MODE: return "UNSUPPORTED_PADDING_MODE(5012): Unsupported padding mode error";
    case RIL_E_UNSUPPORTED_DIGEST: return "UNSUPPORTED_DIGEST(5013): Unsupported digest error";
    case RIL_E_INCOMPATIBLE_DIGEST: return "INCOMPATIBLE_DIGEST(5014): Incompatible digest error";
    case RIL_E_INVAL_EXP_TIME: return "INVAL_EXP_TIME(5015): Invalid expiration time error";
    case RIL_E_INVAL_USR_ID: return "INVAL_USR_ID(5016): Invalid user ID error";
    case RIL_E_INVAL_AUTH_TIMEOUT: return "INVAL_AUTH_TIMEOUT(5017): Invalid authorization timeout error";
    case RIL_E_UNSUPPORTED_KEY_FMT: return "UNSUPPORTED_KEY_FMT(5018): Unsupported key format error";
    case RIL_E_INCOMPATIBLE_KEY_FMT: return "INCOMPATIBLE_KEY_FMT(5019): Incompatible key format error";
    case RIL_E_UNSUPPORTED_KEY_ENC_ALGO: return "UNSUPPORTED_KEY_ENC_ALGO(5020): Unsupported key encryption algorithm (for PKCS8 & PKCS12) error";
    case RIL_E_UNSUPPORTED_KEY_VRFY_ALGO: return "UNSUPPORTED_KEY_VRFY_ALGO(5021): Unsupported key verification algorithm (for PKCS8 & PKCS12) error";
    case RIL_E_INVAL_IN_LEN: return "INVAL_IN_LEN(5022): Invalid input length error";
    case RIL_E_INVAL_KEY_EXPRT_OPTNS: return "INVAL_KEY_EXPRT_OPTNS(5023): Invalid oprions for key export error";
    case RIL_E_DELEGATION_NOT_ALLOWED: return "DELEGATION_NOT_ALLOWED(5024): Delegation not allowed error";
    case RIL_E_KEY_NOT_YET_VALID: return "KEY_NOT_YET_VALID(5025): Key still not valid error";
    case RIL_E_KEY_EXPIRED: return "KEY_EXPIRED(5026): Key has expired error";
    case RIL_E_KEY_USR_NOT_AUTHENTICATED: return "KEY_USR_NOT_AUTHENTICATED(5027): Key user not authenticated error";
    case RIL_E_OUT_PARAMETER_NULL: return "OUT_PARAMETER_NULL(5028): Null output argument error";
    case RIL_E_INVAL_OPERATION_HNDL: return "INVAL_OPERATION_HNDL(5029): Invalid operation handle error";
    case RIL_E_INSUFFICIENT_BUF_SPACE: return "INSUFFICIENT_BUF_SPACE(5030): Insufficient buffer space error";
    case RIL_E_VERIFICATION_FAILED: return "VERIFICATION_FAILED(5031): Verifcation failed error";
    case RIL_E_TOO_MANY_OPS: return "TOO_MANY_OPS(5032): Too many operations error";
    case RIL_E_UNEXPECTED_NULL_PTR: return "UNEXPECTED_NULL_PTR(5033): Unexpected null pointer error";
    case RIL_E_INVAL_KEY_BLOB: return "INVAL_KEY_BLOB(5034): Invalid key blob error";
    case RIL_E_IMPORTED_KEY_NOT_ENC: return "IMPORTED_KEY_NOT_ENC(5035): Imported key not encrypted error";
    case RIL_E_IMPORTED_KEY_DEC_FAIL: return "IMPORTED_KEY_DEC_FAIL(5036): Imported key decryption failed error";
    case RIL_E_IMPORTED_KEY_NOT_SIGNED: return "IMPORTED_KEY_NOT_SIGNED(5037): Imported key not signed error";
    case RIL_E_IMPORTED_KEY_VRFY_FAIL: return "IMPORTED_KEY_VRFY_FAIL(5038): Imported key verification failed error";
    case RIL_E_UNSUPPORTED_TAG: return "UNSUPPORTED_TAG(5039): Unsupported tag error";
    case RIL_E_INVAL_TAG: return "INVAL_TAG(5040): Invalid TAG error";
    case RIL_E_IMPORT_PARAM_MISMATCH: return "IMPORT_PARAM_MISMATCH(5041): Mismatch in import parameters error";
    case RIL_E_SEC_HW_ACCESS_DENIED: return "SEC_HW_ACCESS_DENIED(5042): Secure hardware access denied error";
    case RIL_E_CONCUR_ACCESS_CONFLICT: return "CONCUR_ACCESS_CONFLICT(5043): Concurrent access conflict error";
    case RIL_E_SEC_HW_BUSY: return "SEC_HW_BUSY(5044): Secure hardware busy error";
    case RIL_E_SEC_HW_COM_FAIL: return "SEC_HW_COM_FAIL(5045): Secure hardware communication failed error";
    case RIL_E_UNSUPPORTED_EC_FIELD: return "UNSUPPORTED_EC_FIELD(5046): Unsupported EC field error";
    case RIL_E_MISSING_NONCE: return "MISSING_NONCE(5047): Missing nonce error";
    case RIL_E_INVAL_NONCE: return "INVAL_NONCE(5048): Invalid nonce error";
    case RIL_E_MISSING_MAC_LEN: return "MISSING_MAC_LEN(5049): Missing MAC length error";
    case RIL_E_KEY_RATE_LIMIT_EXCEEDED: return "KEY_RATE_LIMIT_EXCEEDED(5050): Key limit exceeded error";
    case RIL_E_CALLER_NONCE_PROHIBITED: return "CALLER_NONCE_PROHIBITED(5051): Caller nonce proibited error";
    case RIL_E_KEY_MAX_OPS_EXCEEDED: return "KEY_MAX_OPS_EXCEEDED(5052): Key maximum operations exceeded error";
    case RIL_E_INVAL_MAC_LEN: return "INVAL_MAC_LEN(5053): Invalid MAC length error";
    case RIL_E_MISSING_MIN_MAC_LEN: return "MISSING_MIN_MAC_LEN(5054): Missing minimum MAC length error";
    case RIL_E_UNSUPPORTED_MIN_MAC_LEN: return "UNSUPPORTED_MIN_MAC_LEN(5055): Unsupported minimum MAC length error";
    case RIL_E_UNSUPPORTED_KDF: return "UNSUPPORTED_KDF(5056): Unsupported KDF error";
    case RIL_E_UNSUPPORTED_EC_CURVE: return "UNSUPPORTED_EC_CURVE(5057): Unsupported EC curve error";
    case RIL_E_KEY_REQ_UPGRADE: return "KEY_REQ_UPGRADE(5058): Key requires upgrade error";
    case RIL_E_ATTESTATION_CHLNG_MIS: return "ATTESTATION_CHLNG_MIS(5059): Attestation challenge missing error";
    case RIL_E_KM_NOT_CONFGRD: return "KM_NOT_CONFGRD(5060): Keymaster not configured error";
    case RIL_E_ATTESTATION_APPID_MIS: return "ATTESTATION_APPID_MIS(5061): Attestation app ID missing error";
    case RIL_E_CANNOT_ATTEST_IDS: return "CANNOT_ATTEST_IDS(5062): Can not attest IDs error";
    case RIL_E_UNIMPLEMENTED: return "UNIMPLEMENTED(5063): Unimplemented error";
    case RIL_E_VER_MISMATCH: return "VER_MISMATCH(5064): Version mismatch error";
    case RIL_E_SOTER_ERR: return "SOTER_ERR(5065): Soter error";
    case RIL_E_DMA_ERR: return "DMA_ERR(5066): HSDMA error";
    case RIL_E_DIV_ERR: return "DIV_ERR(5067): Divided by error";
    case RIL_E_OVERFLOW_UNDERFLOW: return "OVERFLOW_UNDERFLOW(5068): Arithmetic overflow or underflow error";
    case RIL_E_RNG_UNSEEDED: return "RNG_UNSEEDED(5069): Read from unseeded ring error";
    case RIL_E_MEM_ERR: return "MEM_ERR(5070): Memory read error";
    case RIL_E_MODULUS_ERR: return "MODULUS_ERR(5071): Modulus error";
    case RIL_E_DECODING_ERR: return "DECODING_ERR(5072): Decode error";
    case RIL_E_INVALID_LENGTH: return "INVALID_LENGTH(5073): Invalid length of data error";
